FROM node:20-alpine AS base

# Install necessary libraries for building native modules (like better-sqlite3)
RUN apk add --no-cache python3 make g++ 

WORKDIR /app

# Stage 1: Install dependencies and build the app
FROM base AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Run the production app
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Copy the standalone output and static files generated by Next.js
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Note: The database will be created in /app/.data at runtime 
# because of the standalone layout. Render/Railway volume will be mounted there.

EXPOSE 3000
CMD ["node", "server.js"]